# 基础镜像使用java
FROM openjdk:8-jre

# 作者
MAINTAINER leroey

# VOLUME 指定了临时文件目录为/tmp。
VOLUME /tmp

COPY mall4cloud-leaf/target/mall4cloud-leaf.jar mall4cloud-leaf.jar
COPY mall4cloud-gateway/target/mall4cloud-gateway.jar mall4cloud-gateway.jar
COPY mall4cloud-rbac/target/mall4cloud-rbac.jar mall4cloud-rbac.jar
COPY mall4cloud-search/target/mall4cloud-search.jar mall4cloud-search.jar
COPY mall4cloud-common/mall4cloud-common-core/target/mall4cloud-common-core.jar mall4cloud-common-core.jar
COPY mall4cloud-common/mall4cloud-common-database/target/mall4cloud-common-database.jar mall4cloud-common-database.jar
COPY mall4cloud-common/mall4cloud-common-security/target/mall4cloud-common-security.jar mall4cloud-common-security.jar
COPY mall4cloud-common/mall4cloud-common-rocketmq/target/mall4cloud-common-rocketmq.jar mall4cloud-common-rocketmq.jar
COPY mall4cloud-common/mall4cloud-common-cache/target/mall4cloud-common-cache.jar mall4cloud-common-cache.jar
COPY mall4cloud-common/mall4cloud-common-order/target/mall4cloud-common-order.jar mall4cloud-common-order.jar
COPY mall4cloud-auth/target/mall4cloud-auth.jar mall4cloud-auth.jar
COPY mall4cloud-platform/target/mall4cloud-platform.jar mall4cloud-platform.jar
COPY mall4cloud-user/target/mall4cloud-user.jar mall4cloud-user.jar
COPY mall4cloud-order/target/mall4cloud-order.jar mall4cloud-order.jar
COPY mall4cloud-multishop/target/mall4cloud-multishop.jar mall4cloud-multishop.jar
COPY mall4cloud-api/mall4cloud-api-product/target/mall4cloud-api-product.jar mall4cloud-api-product.jar
COPY mall4cloud-api/mall4cloud-api-platform/target/mall4cloud-api-platform.jar mall4cloud-api-platform.jar
COPY mall4cloud-api/mall4cloud-api-biz/target/mall4cloud-api-biz.jar mall4cloud-api-biz.jar
COPY mall4cloud-api/mall4cloud-api-rbac/target/mall4cloud-api-rbac.jar mall4cloud-api-rbac.jar
COPY mall4cloud-api/mall4cloud-api-leaf/target/mall4cloud-api-leaf.jar mall4cloud-api-leaf.jar
COPY mall4cloud-api/mall4cloud-api-search/target/mall4cloud-api-search.jar mall4cloud-api-search.jar
COPY mall4cloud-api/mall4cloud-api-order/target/mall4cloud-api-order.jar mall4cloud-api-order.jar
COPY mall4cloud-api/mall4cloud-api-user/target/mall4cloud-api-user.jar mall4cloud-api-user.jar
COPY mall4cloud-api/mall4cloud-api-auth/target/mall4cloud-api-auth.jar mall4cloud-api-auth.jar
COPY mall4cloud-api/mall4cloud-api-multishop/target/mall4cloud-api-multishop.jar mall4cloud-api-multishop.jar
COPY mall4cloud-product/target/mall4cloud-product.jar mall4cloud-product.jar
COPY mall4cloud-payment/target/mall4cloud-payment.jar mall4cloud-payment.jar
COPY mall4cloud-biz/target/mall4cloud-biz.jar mall4cloud-biz.jar

COPY bin/start_test.sh /usr/bin/start_test.sh
RUN chmod +x /usr/bin/start_test.sh

#CMD nohup sh -c "start_test.sh"



